services:
  backend:
    build: ./backend
    container_name: e-commerce-backend-container
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: e-commerce-frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules

  admin:
    build: ./admin
    container_name: e-commerce-admin-container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./admin:/app
      - ./admin/node_modules:/app/node_modules